# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisfrontendui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1200))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ezgif.com-gif-maker (1).gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_2.setText("")
        # self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\HP\\OneDrive\\Desktop\\jarvis\\Jarvis_Final-20221202T081334Z-001\\Jarvis_Final\\Iron_Template_1.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_3.setText("")
        # self.label_3.setPixmap(QtGui.QPixmap("C:\\Users\\HP\\OneDrive\\Desktop\\jarvis\\Jarvis_Final-20221202T081334Z-001\\Jarvis_Final\\initial.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label_4.setText("")
        # self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\HP\\OneDrive\\Desktop\\jarvis\\Jarvis_Final-20221202T081334Z-001\\Jarvis_Final\\Jarvis_Gui (1).gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 1000, 110, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\HP\\OneDrive\\Desktop\\jarvis\\Jarvis_Final-20221202T081334Z-001\\Jarvis_Final\\Start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(121, 41))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1500, 1000, 121, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\HP\\OneDrive\\Desktop\\jarvis\\Jarvis_Final-20221202T081334Z-001\\Jarvis_Final\\Quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(121, 41))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.textBrowser.setStyleSheet("background-color:transparent;\n"
        "border-radius:none;\n"
        "color:white;\n"
        "font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.textBrowser_2.setStyleSheet("background-color:transparent;\n"
        "border-radius:none;\n"
        "color:white;\n"
        "font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        MainWindow.setCentralWidget(self.centralwidget)

        # self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # def retranslateUi(self, MainWindow):
        # _translate = QtCore.QCoreApplication.translate
        # MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.pushButton.setText(_translate("MainWindow", "Run"))
        # self.pushButton_3.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
